version: '3.8'

services:
  # ✅ React Frontend Service
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8091:80" # Expose Nginx on port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_network

  # ✅ Go Backend Service
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8090" # Expose Go app on port 8090
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: restaurant_management
    depends_on:
      - database
    networks:
      - app_network

  # ✅ MySQL Database Service
  database:
    container_name: database
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restaurant_management
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
